FROM python:3.11-slim

WORKDIR /app

# Copy the requirements file to the container
COPY requirements.txt requirements.txt

COPY .env .env

# Set up enviroment variables
# ARG SNOWFLAKE_ACCOUNT
# ARG SNOWFLAKE_USER
# ARG SNOWFLAKE_PASSWORD
# ARG SNOWFLAKE_ROLE
# ARG SNOWFLAKE_WAREHOUSE
# ARG SNOWFLAKE_DATABASE
# ARG SNOWFLAKE_SCHEMA
# ARG SNOWFLAKE_STAGE
# ARG DBT_CLOUD_API_KEY

# ENV SNOWFLAKE_ACCOUNT=$SNOWFLAKE_ACCOUNT
# ENV SNOWFLAKE_USER=$SNOWFLAKE_USER
# ENV SNOWFLAKE_PASSWORD=$SNOWFLAKE_PASSWORD
# ENV SNOWFLAKE_ROLE=$SNOWFLAKE_ROLE
# ENV SNOWFLAKE_WAREHOUSE=$SNOWFLAKE_WAREHOUSE
# ENV SNOWFLAKE_DATABASE=$SNOWFLAKE_DATABASE
# ENV SNOWFLAKE_SCHEMA=$SNOWFLAKE_SCHEMA
# ENV SNOWFLAKE_STAGE=$SNOWFLAKE_STAGE
# ENV DBT_CLOUD_API_KEY=$DBT_CLOUD_API_KEY

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code to the container
COPY ./app .

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["streamlit", "run", "Home.py"]