USE ROLE ACCOUNTADMIN;

-- Create a role for the app
CREATE ROLE IF NOT EXISTS APP_ROLE;
grant role APP_ROLE to role ACCOUNTADMIN;

-- Create a database for the app
CREATE DATABASE IF NOT EXISTS APP_DB;

-- Grant privileges on the database to the app role
GRANT OWNERSHIP ON DATABASE APP_DB TO ROLE APP_ROLE COPY CURRENT GRANTS;

-- Create a warehouse for the app
CREATE WAREHOUSE IF NOT EXISTS APP_WAREHOUSE WITH WAREHOUSE_SIZE = 'X-SMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

-- Grant privileges on the warehouse to the app role
GRANT USAGE ON WAREHOUSE APP_WAREHOUSE TO ROLE APP_ROLE;


-- Let's create the schema
use role app_role;
use database app_db;

CREATE SCHEMA IF NOT EXISTS APP_SCHEMA;


-- Create stage
CREATE OR REPLACE STAGE APP_SCHEMA.APP_STAGE;


-- Create blank table for the price lists
CREATE OR REPLACE TABLE APP_SCHEMA.COMPANY_A_PRICE_LISTS (
    SPECIAL STRING,
    ID INTEGER,
    NAME STRING,
    SIZE STRING,
    MATERIAL_COST DECIMAL(10,2),
    HOURS_OF_EFFORT INTEGER,
    LIST_DATE DATE
);

CREATE OR REPLACE TABLE APP_SCHEMA.COMPANY_B_PRICE_LISTS (
    SPECIAL STRING,
    ID INTEGER,
    NAME STRING,
    SIZE STRING,
    MATERIAL_COST DECIMAL(10,2),
    HOURS_OF_EFFORT INTEGER,
    LIST_DATE DATE
);